name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew | chmod +x ./gradle/wrapper/gradle-wrapper.properties

      - name: Build the APK
        run: ./gradlew assembleDebug

      - name: Find APK and print download link
        run: |
          echo "APK files:"
          find $GITHUB_WORKSPACE -type f -name "*.apk" -exec echo {} \;
