name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew | chmod +x ./gradle/wrapper/gradle-wrapper.properties

      - name: Build the APK
        run: ./gradlew assembleDebug

      - name: Copy APK to workspace
        run: |
          mkdir -p apk
          find . -type f -name "*.apk" -exec cp {} apk/ \;
          ls -la apk
    
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: built-apk
          path: apk/
